### ISSUE TITLE
endpoint is deprecated and pending removal

### ISSUE THREAD

**Issue by tonydaly** [clerk/clerk-sdk-ruby#43]
Heya,

I'm following this guide: https://clerk.com/docs/references/ruby/rack-rails

I'm setting the `Authorization` header in my frontend (`@clerk/remix`) and it's all passed through correctly. In my controller I can call `clerk_user` and `clerk_user_signed_in?`. But following the guide when I call `clerk_session` I get the error that the endpoint is deprecated:

```
Clerk::Errors::Fatal: {"errors"=>[{"message"=>"endpoint is deprecated and pending removal", "long_message"=>"This endpoint is deprecated and will be removed in future versions. We strongly recommend switching to networkless verification using short-lived session tokens, which is implemented transparently in all recent SDK versions (e.g. NodeJS SDK https://clerk.com/docs/backend-requests/handling/nodejs#clerk-express-require-auth). For more details on how networkless verification works, refer to our Session Tokens documentation https://clerk.com/docs/backend-requests/resources/session-tokens.", "code"=>"operation_deprecated"}], "clerk_trace_id"=>"b8da8d078aaae67646be5cc80fc40492", "status"=>410}
```

Any help appreciated!

**Comment by dimkl** [comment]
@tonydaly Did the above suggestion resolve your issue?

**Comment by dimkl** [comment]
Closing this issue as it's been stale for a long time. Feel free to re-open!

**Comment by papercrane-elijah** [comment]
Hello folks. Im' curious why this is not in the documentation somewhere? 

https://clerk.com/docs/references/ruby/rack-rails
