### ISSUE TITLE
How to sign out user?

### ISSUE THREAD

**Issue by owenthereal** [clerk/clerk-sdk-ruby#63]
In https://github.com/clerk/clerk-sdk-ruby/blob/main/lib/clerk/authenticatable.rb, I don't see any util method to sign out a user. Is it intentional or is there anything I missed?

**Comment by gkats** [comment]
Hi, @owenthereal. The Clerk Ruby SDK supports [Clerk Backend API](https://clerk.com/docs/reference/backend-api) operations. 

Clerk is "frontend-first". Signing users in (or signing in them up) and sign outs happen with code that runs on the frontend, using one of our frontend SDKs. Under the hood, they all use clerkJS.

Here's a few links from our documentation on how to sign out users with the `<SignOutButton />` or a custom flow, using clerkJS's `signOut` method.

- https://clerk.com/docs/components/unstyled/sign-out-button#sign-out-button
- https://clerk.com/docs/custom-flows/sign-out#build-a-custom-sign-out-flow

Hope the above helps!

I'll close this issue, but feel free to ask more questions in our [Discord community](https://discord.com/invite/b5rXHjAg7A) or [contact support](https://clerk.com/contact/support)
